lua: Update to 5.4.2 and attempt to fix stdio problems when integrating with vlc

diff --git a/mingw-w64-lua/PKGBUILD b/mingw-w64-lua/PKGBUILD
--- a/mingw-w64-lua/PKGBUILD
+++ b/mingw-w64-lua/PKGBUILD
@@ -1,11 +1,12 @@
 # Maintainer: Alexey Pavlov <alexpux@gmail.com>
 # Contributor: David Macek <david.macek.0@gmail.com>
 # Contributor: Felix Huettner <huettner94@gmx.de>
+# Contributor: Ray Donnelly <mingw.android@gmail.com>
 
 _realname=lua
 pkgbase=mingw-w64-${_realname}
 pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
-pkgver=5.3.5
+pkgver=5.4.2
 pkgrel=1
 pkgdesc="A powerful light-weight programming language designed for extending applications. (mingw-w64)"
 arch=('any')
@@ -16,20 +17,24 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-gcc")
 options=('staticlibs' 'strip' 'emptydirs')
 source=("${url}/ftp/lua-${pkgver}.tar.gz"
         'lua.pc'
-        'searchpath.patch'
-        'implib.patch'
+        '0001-When-running-Win32-version-of-luac-on-mintty-or-othe.patch'
+        '0002-Add-Wl-out-implib-liblua.dll.a-to-AR.patch'
+        '0003-Fix-LUA_-DIR-for-MSYS2-FHS-layout.patch'
         'LICENSE')
-sha256sums=('0c2eed3f960446e1a3e4b9a1ca2f3ff893b6ce41942cf54d5dd59ab4b3b058ac'
+sha256sums=('11570d97e9d7303c0a59567ed1ac7c648340cd0db10d5fd594c09223ef2f524f'
             'ca9252633e782b8f85d6a94ea4f6babd4fe30bd759085b373160b1878e36ff78'
-            '3a915911ae680ac3670d6bf96973799baaa7d9c58e6003878eb4369983acc0db'
-            'bbb702be90c8915357f8f24b225bdd53d8c7f18d3eb28bd3ed0f39076ab928fa'
+            'acdd83c0afdf39fe0324a54610b70331e8da2e6167458079e2d1965c6ce3c1a3'
+            'f5b754096ba8117e9e7dedb2e4ecf7b57ab2747e284c14cd51b2cb3353bee3e0'
+            'bae70ef5c4a470527da6696351c9fb90284c6e5739fd2d12d408e5a135a3f1dd'
             '142fb08b41a807b192b4b2c166696a1830a1c97967e5099ad0e579bf500e1da4')
 
 prepare() {
   cd "${srcdir}/${_realname}-${pkgver}"
   cp "${srcdir}/lua.pc" .
-  patch -p0 -i "${srcdir}/implib.patch"
-  patch -p1 -i "${srcdir}/searchpath.patch"
+  rm -f src/iscygpty.{c,h} || true
+  patch -p1 -i "${srcdir}/0001-When-running-Win32-version-of-luac-on-mintty-or-othe.patch"
+  patch -p1 -i "${srcdir}/0002-Add-Wl-out-implib-liblua.dll.a-to-AR.patch"
+  patch -p1 -i "${srcdir}/0003-Fix-LUA_-DIR-for-MSYS2-FHS-layout.patch"
 }
 
 build() {
@@ -40,18 +45,30 @@ build() {
     -e "s|/usr|${MINGW_PREFIX}|g" \
     -i lua.pc
 
-  make -j1 \
+  make \
     AR="ar rcu" \
     RANLIB="ranlib" \
     STRIP="strip" \
     CC="${MINGW_CHOST}-gcc" \
     mingw
+
+  # Check we do not encounter:
+  # "stdin is not a tty"
+  set -x
+  echo "print(\"Hello World\")" > hello-world.lua
+  ./src/luac.exe - < hello-world.lua
+  if [[ ! -f luac.out ]]; then
+    echo "ERROR :: luac.exe stdin read failed to create luac.out"
+    return 1
+  fi
+  rm hello-world.lua
+  rm luac.out
 }
 
 package() {
   cd "${srcdir}/build-${CARCH}"
   make \
-    TO_BIN="lua.exe luac.exe lua53.dll" \
+    TO_BIN="lua.exe luac.exe lua54.dll" \
     TO_LIB="liblua.a liblua.dll.a" \
     INSTALL_TOP="${pkgdir}${MINGW_PREFIX}" \
     INSTALL_MAN="${pkgdir}${MINGW_PREFIX}"/share/man/man1 \
@@ -82,3 +99,4 @@ package() {
   install -m644 doc/*.{gif,png,css,html} "${pkgdir}${MINGW_PREFIX}"/share/doc/lua
   install -Dm644 ../LICENSE "${pkgdir}"${MINGW_PREFIX}/share/licenses/${_realname}/LICENSE
 }
+
